# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-14

    steps:
    - uses: actions/checkout@v3
    - name: build
      run: ARCHS="arm64" ONLY_ACTIVE_ARCH=NO xcodebuild -project CoopFoodScraper.xcodeproj -scheme CoopFoodScraper -sdk macosx14.0 -configuration Debug -derivedDataPath build
    - name: run scraper
      run: ./build/Build/Products/Debug/CoopFoodScraper
    # - name: Build
    #   run: swift build -v
    # - name: Run tests
    #   run: swift test -v
