# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '15 23 * * *' #8時15分
    - cron: '0 0 * * *' #9時
    - cron: '50 0 * * *' #9時50分

jobs:
  build:
    strategy:
      matrix:
        branch: ["main", "develop"]
        

    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ matrix.branch }}
    - name: build
      run: ARCHS="arm64" ONLY_ACTIVE_ARCH=NO xcodebuild -project CoopFoodScraper.xcodeproj -scheme CoopFoodScraper -sdk macosx14.0 -configuration Debug -derivedDataPath build
    - name: run scraper
      run: ./build/Build/Products/Debug/CoopFoodScraper
    - name: setup git
      run: |
        git config --global user.name  "Release Bot"
        git config --global user.email "action@github.com"
        git add .
        git commit -m "Automatically generated"
        git push origin ${{ matrix.branch }}
